### ISSUE TITLE
Fail[ValueError: too many values to unpack] when save model

### ISSUE THREAD

**Issue by CindyHuang-cn** [MtDersvan/tf_playground#12]
Hi, 
   Thanks for your tutorial, but I fail when try to save model, I'm not sure what happended. The error message is:

WARNING:tensorflow:From /home/huangxinyi01/python2.7.8-cpu-tf1.8.0/python2.7.8/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py:1388: get_input_alternatives (from tensorflow.contrib.learn.python.learn.utils.saved_model_export_utils) is deprecated and will be removed in a future version.
Instructions for updating:
Switch to tf.estimator.Exporter and associated utilities.
Traceback (most recent call last):
  File "run_wide_and_deep3.py", line 165, in <module>
    tf.app.run()
  File "/home/huangxinyi01/python2.7.8-cpu-tf1.8.0/python2.7.8/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "run_wide_and_deep3.py", line 162, in main
    train_and_eval()
  File "run_wide_and_deep3.py", line 157, in train_and_eval
    servable_model_path = m.export_savedmodel(servable_model_dir, export_input_fn)
  File "/home/huangxinyi01/python2.7.8-cpu-tf1.8.0/python2.7.8/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1388, in export_savedmodel
    saved_model_export_utils.get_input_alternatives(input_ops))
  File "/home/huangxinyi01/python2.7.8-cpu-tf1.8.0/python2.7.8/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/home/huangxinyi01/python2.7.8-cpu-tf1.8.0/python2.7.8/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/utils/saved_model_export_utils.py", line 173, in get_input_alternatives
    features, unused_labels = input_ops
ValueError: too many values to unpack

  The code is like this: 
    feature_columns = DeepColumns
    feature_spec = tf.feature_column.make_parse_example_spec(feature_columns)
    export_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
    servable_model_dir = "./save_model"
    servable_model_path = m.export_savedmodel(servable_model_dir, export_input_fn)

**Comment by MtDersvan** [comment]
What version of TensorFlow do you use? The code haven't been updated to run on TF 2.0+.
